#!/usr/bin/python

import sys
import os

desktopfile      = 'couturier.desktop'
desktopfile_dest = '/usr/share/applications/%s' % desktopfile

if os.path.islink (desktopfile_dest):
    os.unlink (desktopfile_dest)

sys.exit(0)

