#!/usr/bin/env python

import sys
import os

instpath    = '/usr/lib/couturier'

logo_svg    = '%s/couturier.svg' % instpath

desktopfile      = 'couturier.desktop'
desktopfile_src  = '%s/%s' % (instpath, desktopfile)
desktopfile_dest = '/usr/share/applications/%s' % desktopfile


if os.path.exists (desktopfile_src):

    if os.path.exists (desktopfile_dest):
        os.unlink (desktopfile_dest)

    os.system ('ln -s %s %s' % (desktopfile_src, desktopfile_dest))

    if os.path.exists (logo_svg):
        os.system ('sed -i -e s:Icon=.*:Icon=%s: %s' % (logo_svg, desktopfile_src))

if not os.path.exists (desktopfile_dest):
    print "creation of menu entry failed"

sys.exit(0)

